In [14]:
import lightgbm as lgb
import numpy as np

In [ ]:
rng = np.random.default_rng()

# Training data
data = rng.uniform(size=(500, 10))  # 500 entities, each contains 10 features
label = rng.integers(low=0, high=2, size=(500, ))  # binary target
train_data = lgb.Dataset(data, label=label)

# Validation data (similar process)
val_data = rng.uniform(size=(200, 10))  # 200 validation samples
val_label = rng.integers(low=0, high=2, size=(200, ))

valid_data = lgb.Dataset(val_data, label=val_label, reference=train_data)

print(train_data.data)
print(valid_data.data)

[[0.83191538 0.43082432 0.61159493 ... 0.02113202 0.32720976 0.25947061]
 [0.35072696 0.26869279 0.34498095 ... 0.03030492 0.5966143  0.6757915 ]
 [0.34258914 0.65862602 0.56978158 ... 0.15831254 0.2049655  0.78810314]
 ...
 [0.74349484 0.24667945 0.45132932 ... 0.25207253 0.12402166 0.45062215]
 [0.43962572 0.96279867 0.27555958 ... 0.08946219 0.71084363 0.17679236]
 [0.49693533 0.63915848 0.38472409 ... 0.28064986 0.1414118  0.40500652]]
[[0.97784438 0.39497987 0.72795823 ... 0.85683277 0.19479422 0.40035958]
 [0.77070119 0.12017958 0.1586382  ... 0.04766743 0.13544565 0.11546869]
 [0.39022399 0.11504043 0.5310168  ... 0.9284984  0.77963004 0.43940842]
 ...
 [0.29634063 0.1665193  0.99686719 ... 0.12518529 0.14270314 0.60614914]
 [0.11422799 0.22504857 0.17904542 ... 0.38644922 0.85374618 0.15171242]
 [0.35671714 0.79608643 0.69941126 ... 0.34873733 0.59565564 0.2401036 ]]


In [ ]:
train_data.save_binary('train.bin')
valid_data.save_binary('valid.bin')

[LightGBM] [Warning] File train.bin exists, cannot save binary to it


In [22]:
rng = np.random.default_rng()
w = rng.uniform(size=(500, ))
train_data.set_weight(w)

In [23]:
param = {'num_leaves': 31, 'objective': 'binary'}
param['metric'] = ['auc', 'binary_logloss']

In [ ]:
num_round = 10
bst = lgb.train(
    params=param, 
    train_set=train_data, 
    num_boost_round=num_round, 
    valid_sets=[valid_data])

[LightGBM] [Info] Number of positive: 275, number of negative: 225
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000475 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1670
[LightGBM] [Info] Number of data points in the train set: 500, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.543661 -> initscore=0.175090
[LightGBM] [Info] Start training from score 0.175090
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 